//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170215.1712 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.05.18 at 06:47:37 PM EEST 
//


package lv.lu.df.java.integration.model.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MarketData }
     *
     */
    public MarketData createMarketData() {
        return new MarketData();
    }

    /**
     * Create an instance of {@link Company }
     *
     */
    public Company createMarketDataCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels }
     *
     */
    public Company.SeriesLabels createMarketDataCompanySeriesLabels() {
        return new Company.SeriesLabels();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X }
     *
     */
    public Company.SeriesLabels.X createMarketDataCompanySeriesLabelsX() {
        return new Company.SeriesLabels.X();
    }

    /**
     * Create an instance of {@link Company.Series }
     *
     */
    public Company.Series createMarketDataCompanySeries() {
        return new Company.Series();
    }

    /**
     * Create an instance of {@link Company.Series.Open }
     *
     */
    public Company.Series.Open createMarketDataCompanySeriesOpen() {
        return new Company.Series.Open();
    }

    /**
     * Create an instance of {@link Company.Series.Low }
     *
     */
    public Company.Series.Low createMarketDataCompanySeriesLow() {
        return new Company.Series.Low();
    }

    /**
     * Create an instance of {@link Company.Series.High }
     *
     */
    public Company.Series.High createMarketDataCompanySeriesHigh() {
        return new Company.Series.High();
    }

    /**
     * Create an instance of {@link Company.Series.Close }
     *
     */
    public Company.Series.Close createMarketDataCompanySeriesClose() {
        return new Company.Series.Close();
    }

    /**
     * Create an instance of {@link Company.SeriesDates }
     *
     */
    public Company.SeriesDates createMarketDataCompanySeriesDates() {
        return new Company.SeriesDates();
    }

    /**
     * Create an instance of {@link Company.SeriesLabelCoordinates }
     *
     */
    public Company.SeriesLabelCoordinates createMarketDataCompanySeriesLabelCoordinates() {
        return new Company.SeriesLabelCoordinates();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X.Dates }
     *
     */
    public Company.SeriesLabels.X.Dates createMarketDataCompanySeriesLabelsXDates() {
        return new Company.SeriesLabels.X.Dates();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X.Pos }
     *
     */
    public Company.SeriesLabels.X.Pos createMarketDataCompanySeriesLabelsXPos() {
        return new Company.SeriesLabels.X.Pos();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X.Priorities }
     *
     */
    public Company.SeriesLabels.X.Priorities createMarketDataCompanySeriesLabelsXPriorities() {
        return new Company.SeriesLabels.X.Priorities();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X.Text }
     *
     */
    public Company.SeriesLabels.X.Text createMarketDataCompanySeriesLabelsXText() {
        return new Company.SeriesLabels.X.Text();
    }

    /**
     * Create an instance of {@link Company.SeriesLabels.X.UtcDates }
     *
     */
    public Company.SeriesLabels.X.UtcDates createMarketDataCompanySeriesLabelsXUtcDates() {
        return new Company.SeriesLabels.X.UtcDates();
    }

    /**
     * Create an instance of {@link Company.Series.Open.Values }
     *
     */
    public Company.Series.Open.Values createMarketDataCompanySeriesOpenValues() {
        return new Company.Series.Open.Values();
    }

    /**
     * Create an instance of {@link Company.Series.Low.Values }
     *
     */
    public Company.Series.Low.Values createMarketDataCompanySeriesLowValues() {
        return new Company.Series.Low.Values();
    }

    /**
     * Create an instance of {@link Company.Series.High.Values }
     *
     */
    public Company.Series.High.Values createMarketDataCompanySeriesHighValues() {
        return new Company.Series.High.Values();
    }

    /**
     * Create an instance of {@link Company.Series.Close.Values }
     *
     */
    public Company.Series.Close.Values createMarketDataCompanySeriesCloseValues() {
        return new Company.Series.Close.Values();
    }

}
